# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET 

on:
  push: 
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    steps:

    - uses: actions/checkout@v3
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./Backend
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./Backend

    - name: Publish
      run: dotnet publish -c Release /actions-runner/_work/FileStorage/FileStorage/Backend/

    - name: create .env
      env:
        DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
        JWT_KEY: ${{ secrets.JWT_KEY }}
      run: |
        touch "/actions-runner/_work/FileStorage/FileStorage/Backend/FileStorageAPI/bin/Release/net6.0/publish/.env"
        echo DB_CONNECTION_STRING=$DB_CONNECTION_STRING >> "/actions-runner/_work/FileStorage/FileStorage/Backend/FileStorageAPI/bin/Release/net6.0/publish/.env"
        echo JWT_KEY=$JWT_KEY >> "/actions-runner/_work/FileStorage/FileStorage/Backend/FileStorageAPI/bin/Release/net6.0/publish/.env"
      
    - name: Run
      working-directory: "/actions-runner/_work/FileStorage/FileStorage/Backend/FileStorageAPI/bin/Release/net6.0/publish"
      run: sudo dotnet "FileStorageAPI.dll" &